DROP TABLE IF EXISTS data_provider;
CREATE TABLE data_provider(id VARCHAR(50) PRIMARY KEY , name VARCHAR(50) NOT NULL, provider_type VARCHAR(50) NOT NULL);

DROP TABLE IF EXISTS feed_group;
CREATE TABLE feed_group( id VARCHAR(50) PRIMARY KEY , data_provider_id VARCHAR(50) NOT NULL, name VARCHAR(50) NOT NULL);

DROP TABLE IF EXISTS employee;
CREATE TABLE employee( id VARCHAR(50) PRIMARY KEY , name VARCHAR(50) NOT NULL);

DROP TABLE IF EXISTS address;
CREATE TABLE address( id VARCHAR(50) PRIMARY KEY , emp_id VARCHAR(50) NOT NULL,
 city VARCHAR(50) NOT NULL, CONSTRAINT fk_employee FOREIGN KEY(emp_id) REFERENCES employee(id));